ros__parameters:
  port: "/dev/ttyUSB0"
  frame_id: "bot1/laser_frame"
  base_frame: "bot1/base_link"
  odom_frame: "odom"
  baudrate: 115200
  frequency: 10.0
  angle_min: -180.0
  angle_max: 180.0
  range_min: 0.1
  range_max: 12.0
  sample_rate: 3
  fixed_resolution: true
  inverted: false
  auto_reconnect: true
  intensity: false
  support_motor_dtr: true
  abnormal_check_count: 4
  debug: false
  lidar_type: 1
  device_type: 0
  ignore_array: ""
  reversion: false
  isSingleChannel: true
  intensity_bit: 0
  invalid_range_is_inf: false

